### ISSUE TITLE
Bug: Loading deployment spec from a remote location causes error

### ISSUE THREAD

**Issue by Gaikotsu2** [chucknorris/dropkick#35]
Under the .NET 4.0 framework, dropkick can not load a deployment specification assembly from a remote location. The error message thrown by the CLR is as follows.

System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at dropkick.Engine.DeploymentFinders.AssemblyWasSpecifiedAssumingOnlyOneDeploymentClass.Find(String assemblyName) in c:\Solutions\dk-fc\product\dropkick\Engine\DeploymentFinders\AssemblyWasSpecifiedAssumingOnlyOneDeploymentClass.cs:line 45
   at dropkick.Engine.DeploymentFinders.MultipleFinder.Find(String deployment) in c:\Solutions\dk-fc\product\dropkick\Engine\DeploymentFinders\MultipleFinder.cs:line 25
   at dropkick.Engine.Runner.Deploy(String commandLine) in c:\Solutions\dk-fc\product\dropkick\Engine\Runner.cs:line 66

**Comment by seif** [comment]
I have been banging my head against the exception as well.

One fix is to add a dk.exe.config file with the contents:

```
  <configuration>
       <runtime>
          <loadFromRemoteSources   enabled="true"/>
      </runtime>
  </configuration>
```

Or just right click on the assembly and unblock it!
